version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 9001:9001
    volumes:
      - ./backend/src:/usr/src/app/src
    command: npm run dev
    depends_on:
      - mongo

  backend2:
    build: ./backend2
    ports:
      - 9002:9002
    volumes:
      - ./backend2/src:/usr/src/app/src
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nav
      - MONGO_INITDB_ROOT_PASSWORD=1234

  frontend:
    build: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start