version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 9001:9001
    volumes:
      - ./backend/src:/usr/src/app/src
    command: npm run dev
  frontend:
    build: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start