version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 9001:9001
    command: npm run start
  frontend:
    build: ./frontend
    ports:
      - 3001:3000
    command: npm run start    