version: '3.8'
services:
  frontend:
    build: ./frontend
    # ports:
    #   - 9000:9000
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start
  
  movie-api:
    build: ./movie-api
    # ports:
    #   - 9001:9001
    volumes:
      - ./movie-api/src:/usr/src/app/src
    command: npm run dev
    depends_on:
      - mongo

  placeholder-api:
    build: ./placeholder-api
    # ports:
    #   - 9002:9002
    volumes:
      - ./placeholder-api/src:/usr/src/app/src
    command: npm run dev

  nginx:
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nav
      - MONGO_INITDB_ROOT_PASSWORD=1234