version: '3.8'
services:
  movie-api:
    build: ./movie-api
    ports:
      - 9001:9001
    volumes:
      - ./movie-api/src:/usr/src/app/src
    command: npm run dev
    depends_on:
      - mongo

  placeholder-api:
    build: ./placeholder-api
    ports:
      - 9002:9002
    volumes:
      - ./placeholder-api/src:/usr/src/app/src
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nav
      - MONGO_INITDB_ROOT_PASSWORD=1234

  frontend:
    build: ./frontend
    ports:
      - 9000:9000
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run start